[package]
name = "vanadium"
version = "0.0.1"
authors = ["Edwin Sarver <edwin.l.sarver@gmail.com>"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
bevy_app = "0.14.0"
bevy_core = "0.14.0"
bevy_ecs = "0.14.0"
clap = { version = "4.5.9", features = ["derive", "string", "wrap_help"] }
crossterm = "0.27.0"
ratatui = { version = "0.27.0", features = ["all-widgets", "macros"] }
thiserror = "1.0.63"
tracing = { version = "0.1.40", features = ["log"] }

[lints.clippy]
module-name-repetitions = {level = "allow"}

