[package]
name = "v"
version = "0.0.1"
authors = ["Edwin Sarver <edwin.l.sarver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui="0.14.0"
termion="1.5.6"
